### ISSUE TITLE
RiotX does not load

### ISSUE THREAD

**Issue by albertooka** [vector-im/riotX-android#931]
After updating RiotX to version 0.14.1 on my Android 10 phone, the application does not pass from the logo screen, it loads for a few seconds and then displays a message "RiotX does not respond".

**Comment by BillCarsonFr** [comment]
Thx, we noticed, currently uploading a corrective release

**Comment by albertooka** [comment]
The problem has been fixed in version 0.14.2

**Comment by PopeRigby** [comment]
Doesn't seem to be fixed for me. It's still not loading on 1.4.3

**Comment by PopeRigby** [comment]
Nvm. It's working now.
